service: slackbot-reginald

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

package:
  include:
    - lib
    - func
    - .env
  exclude:
    - .git
    - .gitignore
    - event.json

functions:
  gateway:
    handler: handler.gateway
    events:
      - http:
          path: reginald
          method: post
  participation:
    handler: handler.participation
  positivity:
    handler: handler.positivity
  conceited:
    handler: handler.conceited


# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
