service: slackbot-reginald

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: ["arn:aws:lambda:*:*:function:slackbot-reginald*"]
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
      Resource: ["arn:aws:dynamodb:*:*:table/Teams"]

package:
  include:
    - lib
    - functions
    - .env
  exclude:
    - .git
    - .gitignore
    - event.json

functions:
  gateway:
    handler: handler.gateway
    events:
      - http:
          path: reginald
          method: post
  oauth:
    handler: handler.oauth
    events:
      - http:
          path: reginald/oauth
          method: get
  participation:
    handler: handler.participation
  positivity:
    handler: handler.positivity
  negativity:
    handler: handler.negativity
  conceit:
    handler: handler.conceit


resources:
  Resources:
    TeamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: Teams
